### ISSUE TITLE
Progress Test

### ISSUE THREAD

**Issue by ayukamarudin** [ayukamarudin/CSS3112_SEPT20192020#6]
Dear students,

May if you already do submission, just reconfirm with me before leaving the lab too.

Thank you and Good luck

The submission shall include word/pdf files of your answer, including source codes, screenshot of compiled results. Don't forget to state your name and student ID number.

**Comment by lewis0612** [comment]
Lewis Wong Lee Lei
BCS19090013
[Progress Test.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807023/Progress.Test.docx)

**Comment by galvinugap** [comment]
GALVIN UGAP
BCS19020002
[Progress Test Set B.pdf](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807027/Progress.Test.Set.B.pdf)

**Comment by William-1214** [comment]
William Ting Ging Hung
BCS19090012
Set B
[pt.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807038/pt.docx)

**Comment by slcs33** [comment]
Sean Lau Chan Sheng
BCS19070006
[programming PT.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807040/programming.PT.docx)

**Comment by mohdiqmal** [comment]
Mohamad Iqmal bin Shafiee
BCS19090020
[progress test set c.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807041/Introduction.to.Programming.Progress.Test.docx)

**Comment by Wendyl23** [comment]
WENDY LAU HUI EE
BCS19090022
SET B
[CSS3112 progress test.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807045/CSS3112.progress.test.docx)

**Comment by lawliet0703** [comment]
LING BI HAO
BCS19090009
SET C
[progress test (set c).docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807058/progress.test.set.c.docx)

**Comment by Ellen47** [comment]
ELLEN WONG YII TING
BCS19090023
SET A
[Programming progress test 1.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807061/Programming.progress.test.1.docx)

**Comment by Lee0795** [comment]
Lee Phin Haou
BCS19090003
SET A
[Progress Test.zip](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807064/Progress.Test.zip)

**Comment by mlzm2096** [comment]
Michael Lim Zi Min
BCS19070010
SET A

[CSS3112 SET A.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807127/CSS3112.SET.A.docx)

**Comment by Lee0795** [comment]
Lee Phin Haou
BCS19090003
SET A
[Progress Test.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807068/Progress.Test.docx)

**Comment by eterradric98** [comment]
Mohd Firdaus Abdullah
BCS19020001
SET C
[PT.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807071/PT.docx)

**Comment by conniebong** [comment]
Connie Bong Kho Her
BCS19090010
SET B
[Progress Test.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807075/Progress.Test.docx)

**Comment by davidlim219** [comment]
David Lim
BCS19020005
SET A
[Progress Test.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807080/Progress.Test.docx)

**Comment by Saranya0311** [comment]
Saranya A/P Balasubramaniam
BCS19090011
Set B
[Progress Test Intro to Programming.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807082/Progress.Test.Intro.to.Programming.docx)

**Comment by regisgan** [comment]
Gan Jia Luk
BCS19020006
SetB
[PT1.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807086/PT1.docx)

**Comment by Anderson0802** [comment]
Anderson Wong Soon Chung
BCS19070004
Set C
[Progress Test CSS3112.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807085/Progress.Test.CSS3112.docx)
[PtCSS3112.zip](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807088/PtCSS3112.zip)

**Comment by stc219** [comment]
[pt.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807089/pt.docx)
Siah Tuong Chuan 
BCS19020004 
SET B

**Comment by dennis12ming** [comment]
Dennis Eu Ming
BCS19090017
Set A
[Progress Test.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807087/Progress.Test.docx)

**Comment by pohchen1121** [comment]
Lau Poh Chen
BCS19090016
[progress test.zip](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807094/progress.test.zip)

**Comment by Daniel814402** [comment]
Daniel Chia Wei Fung
BCS19070007
[Progress Test (SET B).zip](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807098/Progress.Test.SET.B.zip)

**Comment by vincentyii** [comment]
Vincent Yii Shu Sheng
BCS19090008
[SET B.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807101/SET.B.docx)

**Comment by KwongJiaJia** [comment]
Kwong Jia Jia 
BCS19090014
[PT1.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807108/PT1.docx)

**Comment by rachel3167** [comment]
Rachel Wong En Lin
BCS19070011

**Comment by Ngong8** [comment]
Ting Siong Heng
BCS19090005
Set C

[Set C Progress Test.pdf](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807109/Set.C.Progress.Test.pdf)

**Comment by AlviaTang1999** [comment]
Alvia Tang Chok Lee
BCS19090004
Set C
[Progresstest.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807110/Progresstest.docx)

**Comment by linusling2000** [comment]
Linus Ling Chee Hua
BCS19070008
Set C
[Progress Text.zip](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807115/Progress.Text.zip)

**Comment by Ernesthii** [comment]
Ernest Hii Qi Shun
BCS19090019
[Progress Test.zip](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807123/Progress.Test.zip)

**Comment by lilianLau** [comment]
Lilian Lau Zhi Ting
BCS19070009
[Progress Test.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807125/Progress.Test.docx)

**Comment by rachel3167** [comment]
Rachel Wong En Lin
BCS19070011
[Progress test.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807126/Progress.test.docx)

**Comment by weiyuan1009** [comment]
Teng Wei Yuan 
BCS19090018
[progresstext.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807134/progresstext.docx)

**Comment by hidayatilias** [comment]
Mohd Nur Hidayat bin Ilias
BCS19090007
SET A 
[Progress Test.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807137/Progress.Test.docx)

**Comment by SiiKing** [comment]
Sii Hoe King
BCS19070005
[progress test (set B).pdf](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807135/progress.test.set.B.pdf)

**Comment by Vss0001** [comment]
VOON SOON SENG
BCS19090001
[progressTest.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807140/progressTest.docx)

**Comment by rnys2000** [comment]
Raymond Ngu Ying Shao
BCS19070001
[Progress Test Set A.pdf](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807143/Progress.Test.Set.A.pdf)

**Comment by weiyuan1009** [comment]
Teng Wei Yuan
BCS19090018 
SET C
[progresstext.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807147/progresstext.docx)

**Comment by kingleong** [comment]
Lau King Leong
BCS19070003
[Progress Test(Lau King Leong BCS19070003).docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807146/Progress.Test.Lau.King.Leong.BCS19070003.docx)

**Comment by rnys2000** [comment]
Raymond Ngu Ying Shao
BCS19070001
Set A
[Progress Test(Set A).pdf](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807152/Progress.Test.Set.A.pdf)

**Comment by StephenYongHuaKiong** [comment]
STEPHEN YONG HUA KIONG BCS19090002 
SET A
[PT PROGRAMING.pdf](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807181/PT.PROGRAMING.pdf)

**Comment by Aderline0312** [comment]
Aderline Song Ke Xin
BCS19090006
SETB

[pt.docx](https://github.com/ayukamarudin/CSS3112_SEPT20192020/files/3807190/pt.docx)
